server:
  port: 8848

spring:
  mvc:
    converters:
      preferred-json-mapper: gson
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/maa4j?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 230306

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: top.chr0nix.maa4j.controller

knife4j:
  enable: true
  setting:
    language: zh_cn

maa4j:
  secret: "maa"
  use_data: false
  ignore_auth: false
  maa_path: "D:\\maa4j\\maa"
  adb_path: "D:\\maa4j\\maa\\adb\\platform-tools\\adb.exe"
  devices:
